Feature   shopping cart destruction
UnixBird-ps/devops21-metodik1-groupwork pull request #50
Opened 2022-04-20 17:04 UTC by MauroCataldi

2022-04-20 17:12 UTC, MauroCataldi commented
ta bort min feature branch efter

2022-04-20 18:39 UTC, UnixBird-ps commented
I think that the buttons in the shopping cart should be outside the table element.
Please fix that and we'll be closer to a merge.

2022-04-20 18:42 UTC, UnixBird-ps requested changes
I think that the buttons in the shopping cart should be outside the table element.
Please fix that and we'll be closer to a merge.

2022-04-21 21:51 UTC, UnixBird-ps approved these changes

2022-04-21 21:54 UTC, merged